[database]
url = "sqlite+aiosqlite:///./tracer_bio3.db"

[monitoring]
interval = 2  # Seconds between metric collection

[processing]
interval = 30  # Seconds between metric processing

[filters]
users = ["francesco-iori", 'root']

[filters.executables]
pipeline_1 = ["stress"]
pipeline_2 = ["stress"]
bioinformatics_pipeline = ["wget", "fastqc", "seqtk", "bwa", "samtools", 'htseq-count']